server:
  port: 8081

spring:
  application:
    name: trading-platform

  datasource:
    url: jdbc:mysql://localhost:3306/trading_platform?createDatabaseIfNotExist=true
    username: root
    password: la19991104
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        type:
          preferred_boolean_jdbc_type: TINYINT
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379
      password:

  threads:
    virtual:
      enabled: true

jwt:
  secret: "Y2xhdWRlLXRyYWRpbmctcGxhdGZvcm0tc2VjcmV0LWtleS1taW4tMzItY2hhcnMtMjAyNA=="
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

logging:
  level:
    com.tradingplatform: INFO

avatar:
  upload-dir: ./uploads/avatars
  max-size: 5242880  # 5 MB
